version: '3.8'

services:
  weather-lcd:
    build: .
    privileged: true
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
      - "/dev/gpiomem:/dev/gpiomem"
    restart: unless-stopped
    env_file: .env
